// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public final class Collector {
  private Collector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_SpanContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_SpanContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_SpanContext_BaggageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_SpanContext_BaggageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Log_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Log_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Reference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Reference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Reporter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Reporter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_MetricsSample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_MetricsSample_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_InternalMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_InternalMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Auth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Auth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_ReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_ReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_collector_ReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_collector_ReportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017collector.proto\022\023lightstep.collector\032\037" +
      "google/protobuf/timestamp.proto\032\034google/" +
      "api/annotations.proto\"\250\001\n\013SpanContext\022\024\n" +
      "\010trace_id\030\001 \001(\004B\0020\001\022\023\n\007span_id\030\002 \001(\004B\0020\001" +
      "\022>\n\007baggage\030\003 \003(\0132-.lightstep.collector." +
      "SpanContext.BaggageEntry\032.\n\014BaggageEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\225\001\n\010Key" +
      "Value\022\013\n\003key\030\001 \001(\t\022\026\n\014string_value\030\002 \001(\t" +
      "H\000\022\027\n\tint_value\030\003 \001(\003B\0020\001H\000\022\026\n\014double_va" +
      "lue\030\004 \001(\001H\000\022\024\n\nbool_value\030\005 \001(\010H\000\022\024\n\njso" +
      "n_value\030\006 \001(\tH\000B\007\n\005value\"c\n\003Log\022-\n\ttimes" +
      "tamp\030\001 \001(\0132\032.google.protobuf.Timestamp\022-" +
      "\n\006fields\030\002 \003(\0132\035.lightstep.collector.Key" +
      "Value\"\266\001\n\tReference\022A\n\014relationship\030\001 \001(" +
      "\0162+.lightstep.collector.Reference.Relati" +
      "onship\0226\n\014span_context\030\002 \001(\0132 .lightstep" +
      ".collector.SpanContext\".\n\014Relationship\022\014" +
      "\n\010CHILD_OF\020\000\022\020\n\014FOLLOWS_FROM\020\001\"\261\002\n\004Span\022" +
      "6\n\014span_context\030\001 \001(\0132 .lightstep.collec" +
      "tor.SpanContext\022\026\n\016operation_name\030\002 \001(\t\022" +
      "2\n\nreferences\030\003 \003(\0132\036.lightstep.collecto" +
      "r.Reference\0223\n\017start_timestamp\030\004 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022\033\n\017duration_mic" +
      "ros\030\005 \001(\004B\0020\001\022+\n\004tags\030\006 \003(\0132\035.lightstep." +
      "collector.KeyValue\022&\n\004logs\030\007 \003(\0132\030.light" +
      "step.collector.Log\"P\n\010Reporter\022\027\n\013report" +
      "er_id\030\001 \001(\004B\0020\001\022+\n\004tags\030\004 \003(\0132\035.lightste" +
      "p.collector.KeyValue\"W\n\rMetricsSample\022\014\n" +
      "\004name\030\001 \001(\t\022\027\n\tint_value\030\002 \001(\003B\0020\001H\000\022\026\n\014" +
      "double_value\030\003 \001(\001H\000B\007\n\005value\"\363\001\n\017Intern" +
      "alMetrics\0223\n\017start_timestamp\030\001 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\033\n\017duration_micro" +
      "s\030\002 \001(\004B\0020\001\022&\n\004logs\030\003 \003(\0132\030.lightstep.co" +
      "llector.Log\0222\n\006counts\030\004 \003(\0132\".lightstep." +
      "collector.MetricsSample\0222\n\006gauges\030\005 \003(\0132" +
      "\".lightstep.collector.MetricsSample\"\034\n\004A" +
      "uth\022\024\n\014access_token\030\001 \001(\t\"\370\001\n\rReportRequ" +
      "est\022/\n\010reporter\030\001 \001(\0132\035.lightstep.collec" +
      "tor.Reporter\022\'\n\004auth\030\002 \001(\0132\031.lightstep.c" +
      "ollector.Auth\022(\n\005spans\030\003 \003(\0132\031.lightstep" +
      ".collector.Span\022#\n\027timestamp_offset_micr" +
      "os\030\005 \001(\003B\0020\001\022>\n\020internal_metrics\030\006 \001(\0132$" +
      ".lightstep.collector.InternalMetrics\",\n\007" +
      "Command\022\017\n\007disable\030\001 \001(\010\022\020\n\010dev_mode\030\002 \001" +
      "(\010\"\340\001\n\016ReportResponse\022.\n\010commands\030\001 \003(\0132" +
      "\034.lightstep.collector.Command\0225\n\021receive" +
      "_timestamp\030\002 \001(\0132\032.google.protobuf.Times" +
      "tamp\0226\n\022transmit_timestamp\030\003 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022\016\n\006errors\030\004 \003(\t\022\020\n\010" +
      "warnings\030\005 \003(\t\022\r\n\005infos\030\006 \003(\t2\225\001\n\020Collec" +
      "torService\022\200\001\n\006Report\022\".lightstep.collec" +
      "tor.ReportRequest\032#.lightstep.collector." +
      "ReportResponse\"-\202\323\344\223\002\'\"\017/api/v2/reports:" +
      "\001*Z\021\022\017/api/v2/reportsB1\n\031com.lightstep.t" +
      "racer.grpcP\001Z\013collectorpb\242\002\004LSPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_lightstep_collector_SpanContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightstep_collector_SpanContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_SpanContext_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", "Baggage", });
    internal_static_lightstep_collector_SpanContext_BaggageEntry_descriptor =
      internal_static_lightstep_collector_SpanContext_descriptor.getNestedTypes().get(0);
    internal_static_lightstep_collector_SpanContext_BaggageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_SpanContext_BaggageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lightstep_collector_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightstep_collector_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_KeyValue_descriptor,
        new java.lang.String[] { "Key", "StringValue", "IntValue", "DoubleValue", "BoolValue", "JsonValue", "Value", });
    internal_static_lightstep_collector_Log_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightstep_collector_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Log_descriptor,
        new java.lang.String[] { "Timestamp", "Fields", });
    internal_static_lightstep_collector_Reference_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightstep_collector_Reference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Reference_descriptor,
        new java.lang.String[] { "Relationship", "SpanContext", });
    internal_static_lightstep_collector_Span_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lightstep_collector_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Span_descriptor,
        new java.lang.String[] { "SpanContext", "OperationName", "References", "StartTimestamp", "DurationMicros", "Tags", "Logs", });
    internal_static_lightstep_collector_Reporter_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lightstep_collector_Reporter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Reporter_descriptor,
        new java.lang.String[] { "ReporterId", "Tags", });
    internal_static_lightstep_collector_MetricsSample_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lightstep_collector_MetricsSample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_MetricsSample_descriptor,
        new java.lang.String[] { "Name", "IntValue", "DoubleValue", "Value", });
    internal_static_lightstep_collector_InternalMetrics_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lightstep_collector_InternalMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_InternalMetrics_descriptor,
        new java.lang.String[] { "StartTimestamp", "DurationMicros", "Logs", "Counts", "Gauges", });
    internal_static_lightstep_collector_Auth_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_lightstep_collector_Auth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Auth_descriptor,
        new java.lang.String[] { "AccessToken", });
    internal_static_lightstep_collector_ReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_lightstep_collector_ReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_ReportRequest_descriptor,
        new java.lang.String[] { "Reporter", "Auth", "Spans", "TimestampOffsetMicros", "InternalMetrics", });
    internal_static_lightstep_collector_Command_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_lightstep_collector_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_Command_descriptor,
        new java.lang.String[] { "Disable", "DevMode", });
    internal_static_lightstep_collector_ReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_lightstep_collector_ReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_collector_ReportResponse_descriptor,
        new java.lang.String[] { "Commands", "ReceiveTimestamp", "TransmitTimestamp", "Errors", "Warnings", "Infos", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
