// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package com.lightstep.tracer.grpc;

public interface IngestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.metrics.IngestResponse)
    com.google.protobuf.MessageOrBuilder {
}
