// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package com.lightstep.tracer.grpc;

public final class Metrics {
  private Metrics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_metrics_MetricPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_metrics_MetricPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_metrics_IngestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_metrics_IngestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_metrics_IngestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_metrics_IngestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetrics.proto\022\021lightstep.metrics\032\017coll" +
      "ector.proto\032\034google/api/annotations.prot" +
      "o\032\036google/protobuf/duration.proto\032\037googl" +
      "e/protobuf/timestamp.proto\"\217\002\n\013MetricPoi" +
      "nt\022+\n\004kind\030\001 \001(\0162\035.lightstep.metrics.Met" +
      "ricKind\022\023\n\013metric_name\030\002 \001(\t\022)\n\005start\030\003 " +
      "\001(\0132\032.google.protobuf.Timestamp\022+\n\010durat" +
      "ion\030\004 \001(\0132\031.google.protobuf.Duration\022-\n\006" +
      "labels\030\005 \003(\0132\035.lightstep.collector.KeyVa" +
      "lue\022\026\n\014uint64_value\030\006 \001(\004H\000\022\026\n\014double_va" +
      "lue\030\007 \001(\001H\000B\007\n\005value\"\211\001\n\rIngestRequest\022\027" +
      "\n\017idempotency_key\030\001 \001(\t\022/\n\010reporter\030\002 \001(" +
      "\0132\035.lightstep.collector.Reporter\022.\n\006poin" +
      "ts\030\003 \003(\0132\036.lightstep.metrics.MetricPoint" +
      "\"\020\n\016IngestResponse*=\n\nMetricKind\022\027\n\023INVA" +
      "LID_METRIC_KIND\020\000\022\013\n\007COUNTER\020\001\022\t\n\005GAUGE\020" +
      "\0022t\n\016MetricsService\022b\n\006Report\022 .lightste" +
      "p.metrics.IngestRequest\032!.lightstep.metr" +
      "ics.IngestResponse\"\023\202\323\344\223\002\r\"\010/metrics:\001*B" +
      "/\n\031com.lightstep.tracer.grpcP\001Z\tmetricsp" +
      "b\242\002\004LSPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lightstep.tracer.grpc.Collector.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_lightstep_metrics_MetricPoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightstep_metrics_MetricPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_metrics_MetricPoint_descriptor,
        new java.lang.String[] { "Kind", "MetricName", "Start", "Duration", "Labels", "Uint64Value", "DoubleValue", "Value", });
    internal_static_lightstep_metrics_IngestRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightstep_metrics_IngestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_metrics_IngestRequest_descriptor,
        new java.lang.String[] { "IdempotencyKey", "Reporter", "Points", });
    internal_static_lightstep_metrics_IngestResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightstep_metrics_IngestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_metrics_IngestResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.lightstep.tracer.grpc.Collector.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
