// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public interface ReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.collector.ReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .lightstep.collector.Command commands = 1;</code>
   */
  java.util.List<com.lightstep.tracer.grpc.Command> 
      getCommandsList();
  /**
   * <code>repeated .lightstep.collector.Command commands = 1;</code>
   */
  com.lightstep.tracer.grpc.Command getCommands(int index);
  /**
   * <code>repeated .lightstep.collector.Command commands = 1;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .lightstep.collector.Command commands = 1;</code>
   */
  java.util.List<? extends com.lightstep.tracer.grpc.CommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .lightstep.collector.Command commands = 1;</code>
   */
  com.lightstep.tracer.grpc.CommandOrBuilder getCommandsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp receive_timestamp = 2;</code>
   */
  boolean hasReceiveTimestamp();
  /**
   * <code>.google.protobuf.Timestamp receive_timestamp = 2;</code>
   */
  com.google.protobuf.Timestamp getReceiveTimestamp();
  /**
   * <code>.google.protobuf.Timestamp receive_timestamp = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getReceiveTimestampOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp transmit_timestamp = 3;</code>
   */
  boolean hasTransmitTimestamp();
  /**
   * <code>.google.protobuf.Timestamp transmit_timestamp = 3;</code>
   */
  com.google.protobuf.Timestamp getTransmitTimestamp();
  /**
   * <code>.google.protobuf.Timestamp transmit_timestamp = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTransmitTimestampOrBuilder();

  /**
   * <code>repeated string errors = 4;</code>
   */
  java.util.List<java.lang.String>
      getErrorsList();
  /**
   * <code>repeated string errors = 4;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated string errors = 4;</code>
   */
  java.lang.String getErrors(int index);
  /**
   * <code>repeated string errors = 4;</code>
   */
  com.google.protobuf.ByteString
      getErrorsBytes(int index);

  /**
   * <code>repeated string warnings = 5;</code>
   */
  java.util.List<java.lang.String>
      getWarningsList();
  /**
   * <code>repeated string warnings = 5;</code>
   */
  int getWarningsCount();
  /**
   * <code>repeated string warnings = 5;</code>
   */
  java.lang.String getWarnings(int index);
  /**
   * <code>repeated string warnings = 5;</code>
   */
  com.google.protobuf.ByteString
      getWarningsBytes(int index);

  /**
   * <code>repeated string infos = 6;</code>
   */
  java.util.List<java.lang.String>
      getInfosList();
  /**
   * <code>repeated string infos = 6;</code>
   */
  int getInfosCount();
  /**
   * <code>repeated string infos = 6;</code>
   */
  java.lang.String getInfos(int index);
  /**
   * <code>repeated string infos = 6;</code>
   */
  com.google.protobuf.ByteString
      getInfosBytes(int index);
}
