// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightstep.proto

package com.lightstep.tracer.grpc.propagation;

public final class Lightstep {
  private Lightstep() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BinaryCarrierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lightstep.BinaryCarrier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
     * </pre>
     *
     * <code>repeated bytes deprecated_text_ctx = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDeprecatedTextCtxList();
    /**
     * <pre>
     * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
     * </pre>
     *
     * <code>repeated bytes deprecated_text_ctx = 1;</code>
     */
    int getDeprecatedTextCtxCount();
    /**
     * <pre>
     * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
     * </pre>
     *
     * <code>repeated bytes deprecated_text_ctx = 1;</code>
     */
    com.google.protobuf.ByteString getDeprecatedTextCtx(int index);

    /**
     * <pre>
     * The Opentracing "basictracer" proto.
     * </pre>
     *
     * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
     */
    boolean hasBasicCtx();
    /**
     * <pre>
     * The Opentracing "basictracer" proto.
     * </pre>
     *
     * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
     */
    com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier getBasicCtx();
    /**
     * <pre>
     * The Opentracing "basictracer" proto.
     * </pre>
     *
     * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
     */
    com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder getBasicCtxOrBuilder();
  }
  /**
   * <pre>
   * The standard carrier for binary context propagation into LightStep.
   * </pre>
   *
   * Protobuf type {@code lightstep.BinaryCarrier}
   */
  public  static final class BinaryCarrier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lightstep.BinaryCarrier)
      BinaryCarrierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BinaryCarrier.newBuilder() to construct.
    private BinaryCarrier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BinaryCarrier() {
      deprecatedTextCtx_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BinaryCarrier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                deprecatedTextCtx_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              deprecatedTextCtx_.add(input.readBytes());
              break;
            }
            case 18: {
              com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder subBuilder = null;
              if (basicCtx_ != null) {
                subBuilder = basicCtx_.toBuilder();
              }
              basicCtx_ = input.readMessage(com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(basicCtx_);
                basicCtx_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          deprecatedTextCtx_ = java.util.Collections.unmodifiableList(deprecatedTextCtx_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BinaryCarrier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BinaryCarrier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.class, com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.Builder.class);
    }

    private int bitField0_;
    public static final int DEPRECATED_TEXT_CTX_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> deprecatedTextCtx_;
    /**
     * <pre>
     * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
     * </pre>
     *
     * <code>repeated bytes deprecated_text_ctx = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDeprecatedTextCtxList() {
      return deprecatedTextCtx_;
    }
    /**
     * <pre>
     * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
     * </pre>
     *
     * <code>repeated bytes deprecated_text_ctx = 1;</code>
     */
    public int getDeprecatedTextCtxCount() {
      return deprecatedTextCtx_.size();
    }
    /**
     * <pre>
     * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
     * </pre>
     *
     * <code>repeated bytes deprecated_text_ctx = 1;</code>
     */
    public com.google.protobuf.ByteString getDeprecatedTextCtx(int index) {
      return deprecatedTextCtx_.get(index);
    }

    public static final int BASIC_CTX_FIELD_NUMBER = 2;
    private com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier basicCtx_;
    /**
     * <pre>
     * The Opentracing "basictracer" proto.
     * </pre>
     *
     * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
     */
    public boolean hasBasicCtx() {
      return basicCtx_ != null;
    }
    /**
     * <pre>
     * The Opentracing "basictracer" proto.
     * </pre>
     *
     * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
     */
    public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier getBasicCtx() {
      return basicCtx_ == null ? com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.getDefaultInstance() : basicCtx_;
    }
    /**
     * <pre>
     * The Opentracing "basictracer" proto.
     * </pre>
     *
     * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
     */
    public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder getBasicCtxOrBuilder() {
      return getBasicCtx();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < deprecatedTextCtx_.size(); i++) {
        output.writeBytes(1, deprecatedTextCtx_.get(i));
      }
      if (basicCtx_ != null) {
        output.writeMessage(2, getBasicCtx());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < deprecatedTextCtx_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(deprecatedTextCtx_.get(i));
        }
        size += dataSize;
        size += 1 * getDeprecatedTextCtxList().size();
      }
      if (basicCtx_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBasicCtx());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier)) {
        return super.equals(obj);
      }
      com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier other = (com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier) obj;

      boolean result = true;
      result = result && getDeprecatedTextCtxList()
          .equals(other.getDeprecatedTextCtxList());
      result = result && (hasBasicCtx() == other.hasBasicCtx());
      if (hasBasicCtx()) {
        result = result && getBasicCtx()
            .equals(other.getBasicCtx());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDeprecatedTextCtxCount() > 0) {
        hash = (37 * hash) + DEPRECATED_TEXT_CTX_FIELD_NUMBER;
        hash = (53 * hash) + getDeprecatedTextCtxList().hashCode();
      }
      if (hasBasicCtx()) {
        hash = (37 * hash) + BASIC_CTX_FIELD_NUMBER;
        hash = (53 * hash) + getBasicCtx().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The standard carrier for binary context propagation into LightStep.
     * </pre>
     *
     * Protobuf type {@code lightstep.BinaryCarrier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lightstep.BinaryCarrier)
        com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BinaryCarrier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BinaryCarrier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.class, com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.Builder.class);
      }

      // Construct using com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deprecatedTextCtx_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (basicCtxBuilder_ == null) {
          basicCtx_ = null;
        } else {
          basicCtx_ = null;
          basicCtxBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BinaryCarrier_descriptor;
      }

      public com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier getDefaultInstanceForType() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.getDefaultInstance();
      }

      public com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier build() {
        com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier buildPartial() {
        com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier result = new com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          deprecatedTextCtx_ = java.util.Collections.unmodifiableList(deprecatedTextCtx_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.deprecatedTextCtx_ = deprecatedTextCtx_;
        if (basicCtxBuilder_ == null) {
          result.basicCtx_ = basicCtx_;
        } else {
          result.basicCtx_ = basicCtxBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier) {
          return mergeFrom((com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier other) {
        if (other == com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier.getDefaultInstance()) return this;
        if (!other.deprecatedTextCtx_.isEmpty()) {
          if (deprecatedTextCtx_.isEmpty()) {
            deprecatedTextCtx_ = other.deprecatedTextCtx_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDeprecatedTextCtxIsMutable();
            deprecatedTextCtx_.addAll(other.deprecatedTextCtx_);
          }
          onChanged();
        }
        if (other.hasBasicCtx()) {
          mergeBasicCtx(other.getBasicCtx());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> deprecatedTextCtx_ = java.util.Collections.emptyList();
      private void ensureDeprecatedTextCtxIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          deprecatedTextCtx_ = new java.util.ArrayList<com.google.protobuf.ByteString>(deprecatedTextCtx_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDeprecatedTextCtxList() {
        return java.util.Collections.unmodifiableList(deprecatedTextCtx_);
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public int getDeprecatedTextCtxCount() {
        return deprecatedTextCtx_.size();
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public com.google.protobuf.ByteString getDeprecatedTextCtx(int index) {
        return deprecatedTextCtx_.get(index);
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public Builder setDeprecatedTextCtx(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeprecatedTextCtxIsMutable();
        deprecatedTextCtx_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public Builder addDeprecatedTextCtx(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeprecatedTextCtxIsMutable();
        deprecatedTextCtx_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public Builder addAllDeprecatedTextCtx(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDeprecatedTextCtxIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deprecatedTextCtx_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * "text_ctx" was deprecated following lightstep-tracer-cpp-0.36
       * </pre>
       *
       * <code>repeated bytes deprecated_text_ctx = 1;</code>
       */
      public Builder clearDeprecatedTextCtx() {
        deprecatedTextCtx_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier basicCtx_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder> basicCtxBuilder_;
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public boolean hasBasicCtx() {
        return basicCtxBuilder_ != null || basicCtx_ != null;
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier getBasicCtx() {
        if (basicCtxBuilder_ == null) {
          return basicCtx_ == null ? com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.getDefaultInstance() : basicCtx_;
        } else {
          return basicCtxBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public Builder setBasicCtx(com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier value) {
        if (basicCtxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          basicCtx_ = value;
          onChanged();
        } else {
          basicCtxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public Builder setBasicCtx(
          com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder builderForValue) {
        if (basicCtxBuilder_ == null) {
          basicCtx_ = builderForValue.build();
          onChanged();
        } else {
          basicCtxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public Builder mergeBasicCtx(com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier value) {
        if (basicCtxBuilder_ == null) {
          if (basicCtx_ != null) {
            basicCtx_ =
              com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.newBuilder(basicCtx_).mergeFrom(value).buildPartial();
          } else {
            basicCtx_ = value;
          }
          onChanged();
        } else {
          basicCtxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public Builder clearBasicCtx() {
        if (basicCtxBuilder_ == null) {
          basicCtx_ = null;
          onChanged();
        } else {
          basicCtx_ = null;
          basicCtxBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder getBasicCtxBuilder() {
        
        onChanged();
        return getBasicCtxFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder getBasicCtxOrBuilder() {
        if (basicCtxBuilder_ != null) {
          return basicCtxBuilder_.getMessageOrBuilder();
        } else {
          return basicCtx_ == null ?
              com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.getDefaultInstance() : basicCtx_;
        }
      }
      /**
       * <pre>
       * The Opentracing "basictracer" proto.
       * </pre>
       *
       * <code>.lightstep.BasicTracerCarrier basic_ctx = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder> 
          getBasicCtxFieldBuilder() {
        if (basicCtxBuilder_ == null) {
          basicCtxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder>(
                  getBasicCtx(),
                  getParentForChildren(),
                  isClean());
          basicCtx_ = null;
        }
        return basicCtxBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lightstep.BinaryCarrier)
    }

    // @@protoc_insertion_point(class_scope:lightstep.BinaryCarrier)
    private static final com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier();
    }

    public static com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BinaryCarrier>
        PARSER = new com.google.protobuf.AbstractParser<BinaryCarrier>() {
      public BinaryCarrier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BinaryCarrier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BinaryCarrier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BinaryCarrier> getParserForType() {
      return PARSER;
    }

    public com.lightstep.tracer.grpc.propagation.Lightstep.BinaryCarrier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BasicTracerCarrierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lightstep.BasicTracerCarrier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>fixed64 trace_id = 1;</code>
     */
    long getTraceId();

    /**
     * <code>fixed64 span_id = 2;</code>
     */
    long getSpanId();

    /**
     * <code>bool sampled = 3;</code>
     */
    boolean getSampled();

    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */
    int getBaggageItemsCount();
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */
    boolean containsBaggageItems(
        java.lang.String key);
    /**
     * Use {@link #getBaggageItemsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getBaggageItems();
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getBaggageItemsMap();
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */

    java.lang.String getBaggageItemsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */

    java.lang.String getBaggageItemsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Copy of https://github.com/opentracing/basictracer-go/blob/master/wire/wire.proto
   * </pre>
   *
   * Protobuf type {@code lightstep.BasicTracerCarrier}
   */
  public  static final class BasicTracerCarrier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lightstep.BasicTracerCarrier)
      BasicTracerCarrierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BasicTracerCarrier.newBuilder() to construct.
    private BasicTracerCarrier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BasicTracerCarrier() {
      traceId_ = 0L;
      spanId_ = 0L;
      sampled_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BasicTracerCarrier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              traceId_ = input.readFixed64();
              break;
            }
            case 17: {

              spanId_ = input.readFixed64();
              break;
            }
            case 24: {

              sampled_ = input.readBool();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                baggageItems_ = com.google.protobuf.MapField.newMapField(
                    BaggageItemsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              baggageItems__ = input.readMessage(
                  BaggageItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              baggageItems_.getMutableMap().put(
                  baggageItems__.getKey(), baggageItems__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BasicTracerCarrier_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetBaggageItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BasicTracerCarrier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.class, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder.class);
    }

    private int bitField0_;
    public static final int TRACE_ID_FIELD_NUMBER = 1;
    private long traceId_;
    /**
     * <code>fixed64 trace_id = 1;</code>
     */
    public long getTraceId() {
      return traceId_;
    }

    public static final int SPAN_ID_FIELD_NUMBER = 2;
    private long spanId_;
    /**
     * <code>fixed64 span_id = 2;</code>
     */
    public long getSpanId() {
      return spanId_;
    }

    public static final int SAMPLED_FIELD_NUMBER = 3;
    private boolean sampled_;
    /**
     * <code>bool sampled = 3;</code>
     */
    public boolean getSampled() {
      return sampled_;
    }

    public static final int BAGGAGE_ITEMS_FIELD_NUMBER = 4;
    private static final class BaggageItemsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BasicTracerCarrier_BaggageItemsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> baggageItems_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetBaggageItems() {
      if (baggageItems_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BaggageItemsDefaultEntryHolder.defaultEntry);
      }
      return baggageItems_;
    }

    public int getBaggageItemsCount() {
      return internalGetBaggageItems().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */

    public boolean containsBaggageItems(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetBaggageItems().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBaggageItemsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getBaggageItems() {
      return getBaggageItemsMap();
    }
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getBaggageItemsMap() {
      return internalGetBaggageItems().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */

    public java.lang.String getBaggageItemsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetBaggageItems().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; baggage_items = 4;</code>
     */

    public java.lang.String getBaggageItemsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetBaggageItems().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (traceId_ != 0L) {
        output.writeFixed64(1, traceId_);
      }
      if (spanId_ != 0L) {
        output.writeFixed64(2, spanId_);
      }
      if (sampled_ != false) {
        output.writeBool(3, sampled_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetBaggageItems(),
          BaggageItemsDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (traceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, traceId_);
      }
      if (spanId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, spanId_);
      }
      if (sampled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, sampled_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetBaggageItems().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        baggageItems__ = BaggageItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, baggageItems__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier)) {
        return super.equals(obj);
      }
      com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier other = (com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier) obj;

      boolean result = true;
      result = result && (getTraceId()
          == other.getTraceId());
      result = result && (getSpanId()
          == other.getSpanId());
      result = result && (getSampled()
          == other.getSampled());
      result = result && internalGetBaggageItems().equals(
          other.internalGetBaggageItems());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTraceId());
      hash = (37 * hash) + SPAN_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSpanId());
      hash = (37 * hash) + SAMPLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSampled());
      if (!internalGetBaggageItems().getMap().isEmpty()) {
        hash = (37 * hash) + BAGGAGE_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetBaggageItems().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Copy of https://github.com/opentracing/basictracer-go/blob/master/wire/wire.proto
     * </pre>
     *
     * Protobuf type {@code lightstep.BasicTracerCarrier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lightstep.BasicTracerCarrier)
        com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BasicTracerCarrier_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetBaggageItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableBaggageItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BasicTracerCarrier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.class, com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.Builder.class);
      }

      // Construct using com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        traceId_ = 0L;

        spanId_ = 0L;

        sampled_ = false;

        internalGetMutableBaggageItems().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.internal_static_lightstep_BasicTracerCarrier_descriptor;
      }

      public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier getDefaultInstanceForType() {
        return com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.getDefaultInstance();
      }

      public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier build() {
        com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier buildPartial() {
        com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier result = new com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.traceId_ = traceId_;
        result.spanId_ = spanId_;
        result.sampled_ = sampled_;
        result.baggageItems_ = internalGetBaggageItems();
        result.baggageItems_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier) {
          return mergeFrom((com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier other) {
        if (other == com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier.getDefaultInstance()) return this;
        if (other.getTraceId() != 0L) {
          setTraceId(other.getTraceId());
        }
        if (other.getSpanId() != 0L) {
          setSpanId(other.getSpanId());
        }
        if (other.getSampled() != false) {
          setSampled(other.getSampled());
        }
        internalGetMutableBaggageItems().mergeFrom(
            other.internalGetBaggageItems());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long traceId_ ;
      /**
       * <code>fixed64 trace_id = 1;</code>
       */
      public long getTraceId() {
        return traceId_;
      }
      /**
       * <code>fixed64 trace_id = 1;</code>
       */
      public Builder setTraceId(long value) {
        
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 trace_id = 1;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = 0L;
        onChanged();
        return this;
      }

      private long spanId_ ;
      /**
       * <code>fixed64 span_id = 2;</code>
       */
      public long getSpanId() {
        return spanId_;
      }
      /**
       * <code>fixed64 span_id = 2;</code>
       */
      public Builder setSpanId(long value) {
        
        spanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 span_id = 2;</code>
       */
      public Builder clearSpanId() {
        
        spanId_ = 0L;
        onChanged();
        return this;
      }

      private boolean sampled_ ;
      /**
       * <code>bool sampled = 3;</code>
       */
      public boolean getSampled() {
        return sampled_;
      }
      /**
       * <code>bool sampled = 3;</code>
       */
      public Builder setSampled(boolean value) {
        
        sampled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sampled = 3;</code>
       */
      public Builder clearSampled() {
        
        sampled_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> baggageItems_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetBaggageItems() {
        if (baggageItems_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BaggageItemsDefaultEntryHolder.defaultEntry);
        }
        return baggageItems_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableBaggageItems() {
        onChanged();;
        if (baggageItems_ == null) {
          baggageItems_ = com.google.protobuf.MapField.newMapField(
              BaggageItemsDefaultEntryHolder.defaultEntry);
        }
        if (!baggageItems_.isMutable()) {
          baggageItems_ = baggageItems_.copy();
        }
        return baggageItems_;
      }

      public int getBaggageItemsCount() {
        return internalGetBaggageItems().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */

      public boolean containsBaggageItems(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetBaggageItems().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBaggageItemsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getBaggageItems() {
        return getBaggageItemsMap();
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getBaggageItemsMap() {
        return internalGetBaggageItems().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */

      public java.lang.String getBaggageItemsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetBaggageItems().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */

      public java.lang.String getBaggageItemsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetBaggageItems().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearBaggageItems() {
        internalGetMutableBaggageItems().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */

      public Builder removeBaggageItems(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBaggageItems().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableBaggageItems() {
        return internalGetMutableBaggageItems().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */
      public Builder putBaggageItems(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBaggageItems().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; baggage_items = 4;</code>
       */

      public Builder putAllBaggageItems(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableBaggageItems().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lightstep.BasicTracerCarrier)
    }

    // @@protoc_insertion_point(class_scope:lightstep.BasicTracerCarrier)
    private static final com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier();
    }

    public static com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BasicTracerCarrier>
        PARSER = new com.google.protobuf.AbstractParser<BasicTracerCarrier>() {
      public BasicTracerCarrier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BasicTracerCarrier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BasicTracerCarrier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BasicTracerCarrier> getParserForType() {
      return PARSER;
    }

    public com.lightstep.tracer.grpc.propagation.Lightstep.BasicTracerCarrier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_BinaryCarrier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_BinaryCarrier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_BasicTracerCarrier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_BasicTracerCarrier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightstep_BasicTracerCarrier_BaggageItemsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightstep_BasicTracerCarrier_BaggageItemsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017lightstep.proto\022\tlightstep\"^\n\rBinaryCa" +
      "rrier\022\033\n\023deprecated_text_ctx\030\001 \003(\014\0220\n\tba" +
      "sic_ctx\030\002 \001(\0132\035.lightstep.BasicTracerCar" +
      "rier\"\305\001\n\022BasicTracerCarrier\022\020\n\010trace_id\030" +
      "\001 \001(\006\022\017\n\007span_id\030\002 \001(\006\022\017\n\007sampled\030\003 \001(\010\022" +
      "F\n\rbaggage_items\030\004 \003(\0132/.lightstep.Basic" +
      "TracerCarrier.BaggageItemsEntry\0323\n\021Bagga" +
      "geItemsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B4\n%com.lightstep.tracer.grpc.propag" +
      "ationZ\013lightsteppbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightstep_BinaryCarrier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightstep_BinaryCarrier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_BinaryCarrier_descriptor,
        new java.lang.String[] { "DeprecatedTextCtx", "BasicCtx", });
    internal_static_lightstep_BasicTracerCarrier_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightstep_BasicTracerCarrier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_BasicTracerCarrier_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", "Sampled", "BaggageItems", });
    internal_static_lightstep_BasicTracerCarrier_BaggageItemsEntry_descriptor =
      internal_static_lightstep_BasicTracerCarrier_descriptor.getNestedTypes().get(0);
    internal_static_lightstep_BasicTracerCarrier_BaggageItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightstep_BasicTracerCarrier_BaggageItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
