// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

public interface MetricsSampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightstep.collector.MetricsSample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 int_value = 2;</code>
   */
  long getIntValue();

  /**
   * <code>double double_value = 3;</code>
   */
  double getDoubleValue();

  public com.lightstep.tracer.grpc.MetricsSample.ValueCase getValueCase();
}
