// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

package com.lightstep.tracer.grpc;

/**
 * Protobuf type {@code lightstep.collector.ReportRequest}
 */
public  final class ReportRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightstep.collector.ReportRequest)
    ReportRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportRequest.newBuilder() to construct.
  private ReportRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportRequest() {
    spans_ = java.util.Collections.emptyList();
    timestampOffsetMicros_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.lightstep.tracer.grpc.Reporter.Builder subBuilder = null;
            if (reporter_ != null) {
              subBuilder = reporter_.toBuilder();
            }
            reporter_ = input.readMessage(com.lightstep.tracer.grpc.Reporter.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reporter_);
              reporter_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.lightstep.tracer.grpc.Auth.Builder subBuilder = null;
            if (auth_ != null) {
              subBuilder = auth_.toBuilder();
            }
            auth_ = input.readMessage(com.lightstep.tracer.grpc.Auth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(auth_);
              auth_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              spans_ = new java.util.ArrayList<com.lightstep.tracer.grpc.Span>();
              mutable_bitField0_ |= 0x00000004;
            }
            spans_.add(
                input.readMessage(com.lightstep.tracer.grpc.Span.parser(), extensionRegistry));
            break;
          }
          case 40: {

            timestampOffsetMicros_ = input.readInt64();
            break;
          }
          case 50: {
            com.lightstep.tracer.grpc.InternalMetrics.Builder subBuilder = null;
            if (internalMetrics_ != null) {
              subBuilder = internalMetrics_.toBuilder();
            }
            internalMetrics_ = input.readMessage(com.lightstep.tracer.grpc.InternalMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(internalMetrics_);
              internalMetrics_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        spans_ = java.util.Collections.unmodifiableList(spans_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_ReportRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_ReportRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lightstep.tracer.grpc.ReportRequest.class, com.lightstep.tracer.grpc.ReportRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REPORTER_FIELD_NUMBER = 1;
  private com.lightstep.tracer.grpc.Reporter reporter_;
  /**
   * <code>.lightstep.collector.Reporter reporter = 1;</code>
   */
  public boolean hasReporter() {
    return reporter_ != null;
  }
  /**
   * <code>.lightstep.collector.Reporter reporter = 1;</code>
   */
  public com.lightstep.tracer.grpc.Reporter getReporter() {
    return reporter_ == null ? com.lightstep.tracer.grpc.Reporter.getDefaultInstance() : reporter_;
  }
  /**
   * <code>.lightstep.collector.Reporter reporter = 1;</code>
   */
  public com.lightstep.tracer.grpc.ReporterOrBuilder getReporterOrBuilder() {
    return getReporter();
  }

  public static final int AUTH_FIELD_NUMBER = 2;
  private com.lightstep.tracer.grpc.Auth auth_;
  /**
   * <code>.lightstep.collector.Auth auth = 2;</code>
   */
  public boolean hasAuth() {
    return auth_ != null;
  }
  /**
   * <code>.lightstep.collector.Auth auth = 2;</code>
   */
  public com.lightstep.tracer.grpc.Auth getAuth() {
    return auth_ == null ? com.lightstep.tracer.grpc.Auth.getDefaultInstance() : auth_;
  }
  /**
   * <code>.lightstep.collector.Auth auth = 2;</code>
   */
  public com.lightstep.tracer.grpc.AuthOrBuilder getAuthOrBuilder() {
    return getAuth();
  }

  public static final int SPANS_FIELD_NUMBER = 3;
  private java.util.List<com.lightstep.tracer.grpc.Span> spans_;
  /**
   * <code>repeated .lightstep.collector.Span spans = 3;</code>
   */
  public java.util.List<com.lightstep.tracer.grpc.Span> getSpansList() {
    return spans_;
  }
  /**
   * <code>repeated .lightstep.collector.Span spans = 3;</code>
   */
  public java.util.List<? extends com.lightstep.tracer.grpc.SpanOrBuilder> 
      getSpansOrBuilderList() {
    return spans_;
  }
  /**
   * <code>repeated .lightstep.collector.Span spans = 3;</code>
   */
  public int getSpansCount() {
    return spans_.size();
  }
  /**
   * <code>repeated .lightstep.collector.Span spans = 3;</code>
   */
  public com.lightstep.tracer.grpc.Span getSpans(int index) {
    return spans_.get(index);
  }
  /**
   * <code>repeated .lightstep.collector.Span spans = 3;</code>
   */
  public com.lightstep.tracer.grpc.SpanOrBuilder getSpansOrBuilder(
      int index) {
    return spans_.get(index);
  }

  public static final int TIMESTAMP_OFFSET_MICROS_FIELD_NUMBER = 5;
  private long timestampOffsetMicros_;
  /**
   * <code>int64 timestamp_offset_micros = 5;</code>
   */
  public long getTimestampOffsetMicros() {
    return timestampOffsetMicros_;
  }

  public static final int INTERNAL_METRICS_FIELD_NUMBER = 6;
  private com.lightstep.tracer.grpc.InternalMetrics internalMetrics_;
  /**
   * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
   */
  public boolean hasInternalMetrics() {
    return internalMetrics_ != null;
  }
  /**
   * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
   */
  public com.lightstep.tracer.grpc.InternalMetrics getInternalMetrics() {
    return internalMetrics_ == null ? com.lightstep.tracer.grpc.InternalMetrics.getDefaultInstance() : internalMetrics_;
  }
  /**
   * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
   */
  public com.lightstep.tracer.grpc.InternalMetricsOrBuilder getInternalMetricsOrBuilder() {
    return getInternalMetrics();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reporter_ != null) {
      output.writeMessage(1, getReporter());
    }
    if (auth_ != null) {
      output.writeMessage(2, getAuth());
    }
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(3, spans_.get(i));
    }
    if (timestampOffsetMicros_ != 0L) {
      output.writeInt64(5, timestampOffsetMicros_);
    }
    if (internalMetrics_ != null) {
      output.writeMessage(6, getInternalMetrics());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reporter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReporter());
    }
    if (auth_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuth());
    }
    for (int i = 0; i < spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, spans_.get(i));
    }
    if (timestampOffsetMicros_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timestampOffsetMicros_);
    }
    if (internalMetrics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getInternalMetrics());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lightstep.tracer.grpc.ReportRequest)) {
      return super.equals(obj);
    }
    com.lightstep.tracer.grpc.ReportRequest other = (com.lightstep.tracer.grpc.ReportRequest) obj;

    boolean result = true;
    result = result && (hasReporter() == other.hasReporter());
    if (hasReporter()) {
      result = result && getReporter()
          .equals(other.getReporter());
    }
    result = result && (hasAuth() == other.hasAuth());
    if (hasAuth()) {
      result = result && getAuth()
          .equals(other.getAuth());
    }
    result = result && getSpansList()
        .equals(other.getSpansList());
    result = result && (getTimestampOffsetMicros()
        == other.getTimestampOffsetMicros());
    result = result && (hasInternalMetrics() == other.hasInternalMetrics());
    if (hasInternalMetrics()) {
      result = result && getInternalMetrics()
          .equals(other.getInternalMetrics());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReporter()) {
      hash = (37 * hash) + REPORTER_FIELD_NUMBER;
      hash = (53 * hash) + getReporter().hashCode();
    }
    if (hasAuth()) {
      hash = (37 * hash) + AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getAuth().hashCode();
    }
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_OFFSET_MICROS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampOffsetMicros());
    if (hasInternalMetrics()) {
      hash = (37 * hash) + INTERNAL_METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getInternalMetrics().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstep.tracer.grpc.ReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lightstep.tracer.grpc.ReportRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightstep.collector.ReportRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightstep.collector.ReportRequest)
      com.lightstep.tracer.grpc.ReportRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_ReportRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_ReportRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstep.tracer.grpc.ReportRequest.class, com.lightstep.tracer.grpc.ReportRequest.Builder.class);
    }

    // Construct using com.lightstep.tracer.grpc.ReportRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSpansFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (reporterBuilder_ == null) {
        reporter_ = null;
      } else {
        reporter_ = null;
        reporterBuilder_ = null;
      }
      if (authBuilder_ == null) {
        auth_ = null;
      } else {
        auth_ = null;
        authBuilder_ = null;
      }
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        spansBuilder_.clear();
      }
      timestampOffsetMicros_ = 0L;

      if (internalMetricsBuilder_ == null) {
        internalMetrics_ = null;
      } else {
        internalMetrics_ = null;
        internalMetricsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lightstep.tracer.grpc.Collector.internal_static_lightstep_collector_ReportRequest_descriptor;
    }

    @java.lang.Override
    public com.lightstep.tracer.grpc.ReportRequest getDefaultInstanceForType() {
      return com.lightstep.tracer.grpc.ReportRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.lightstep.tracer.grpc.ReportRequest build() {
      com.lightstep.tracer.grpc.ReportRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lightstep.tracer.grpc.ReportRequest buildPartial() {
      com.lightstep.tracer.grpc.ReportRequest result = new com.lightstep.tracer.grpc.ReportRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (reporterBuilder_ == null) {
        result.reporter_ = reporter_;
      } else {
        result.reporter_ = reporterBuilder_.build();
      }
      if (authBuilder_ == null) {
        result.auth_ = auth_;
      } else {
        result.auth_ = authBuilder_.build();
      }
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
      result.timestampOffsetMicros_ = timestampOffsetMicros_;
      if (internalMetricsBuilder_ == null) {
        result.internalMetrics_ = internalMetrics_;
      } else {
        result.internalMetrics_ = internalMetricsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lightstep.tracer.grpc.ReportRequest) {
        return mergeFrom((com.lightstep.tracer.grpc.ReportRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lightstep.tracer.grpc.ReportRequest other) {
      if (other == com.lightstep.tracer.grpc.ReportRequest.getDefaultInstance()) return this;
      if (other.hasReporter()) {
        mergeReporter(other.getReporter());
      }
      if (other.hasAuth()) {
        mergeAuth(other.getAuth());
      }
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000004);
            spansBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpansFieldBuilder() : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      if (other.getTimestampOffsetMicros() != 0L) {
        setTimestampOffsetMicros(other.getTimestampOffsetMicros());
      }
      if (other.hasInternalMetrics()) {
        mergeInternalMetrics(other.getInternalMetrics());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lightstep.tracer.grpc.ReportRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lightstep.tracer.grpc.ReportRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.lightstep.tracer.grpc.Reporter reporter_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.Reporter, com.lightstep.tracer.grpc.Reporter.Builder, com.lightstep.tracer.grpc.ReporterOrBuilder> reporterBuilder_;
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public boolean hasReporter() {
      return reporterBuilder_ != null || reporter_ != null;
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public com.lightstep.tracer.grpc.Reporter getReporter() {
      if (reporterBuilder_ == null) {
        return reporter_ == null ? com.lightstep.tracer.grpc.Reporter.getDefaultInstance() : reporter_;
      } else {
        return reporterBuilder_.getMessage();
      }
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public Builder setReporter(com.lightstep.tracer.grpc.Reporter value) {
      if (reporterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reporter_ = value;
        onChanged();
      } else {
        reporterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public Builder setReporter(
        com.lightstep.tracer.grpc.Reporter.Builder builderForValue) {
      if (reporterBuilder_ == null) {
        reporter_ = builderForValue.build();
        onChanged();
      } else {
        reporterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public Builder mergeReporter(com.lightstep.tracer.grpc.Reporter value) {
      if (reporterBuilder_ == null) {
        if (reporter_ != null) {
          reporter_ =
            com.lightstep.tracer.grpc.Reporter.newBuilder(reporter_).mergeFrom(value).buildPartial();
        } else {
          reporter_ = value;
        }
        onChanged();
      } else {
        reporterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public Builder clearReporter() {
      if (reporterBuilder_ == null) {
        reporter_ = null;
        onChanged();
      } else {
        reporter_ = null;
        reporterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public com.lightstep.tracer.grpc.Reporter.Builder getReporterBuilder() {
      
      onChanged();
      return getReporterFieldBuilder().getBuilder();
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    public com.lightstep.tracer.grpc.ReporterOrBuilder getReporterOrBuilder() {
      if (reporterBuilder_ != null) {
        return reporterBuilder_.getMessageOrBuilder();
      } else {
        return reporter_ == null ?
            com.lightstep.tracer.grpc.Reporter.getDefaultInstance() : reporter_;
      }
    }
    /**
     * <code>.lightstep.collector.Reporter reporter = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.Reporter, com.lightstep.tracer.grpc.Reporter.Builder, com.lightstep.tracer.grpc.ReporterOrBuilder> 
        getReporterFieldBuilder() {
      if (reporterBuilder_ == null) {
        reporterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lightstep.tracer.grpc.Reporter, com.lightstep.tracer.grpc.Reporter.Builder, com.lightstep.tracer.grpc.ReporterOrBuilder>(
                getReporter(),
                getParentForChildren(),
                isClean());
        reporter_ = null;
      }
      return reporterBuilder_;
    }

    private com.lightstep.tracer.grpc.Auth auth_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.Auth, com.lightstep.tracer.grpc.Auth.Builder, com.lightstep.tracer.grpc.AuthOrBuilder> authBuilder_;
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public boolean hasAuth() {
      return authBuilder_ != null || auth_ != null;
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public com.lightstep.tracer.grpc.Auth getAuth() {
      if (authBuilder_ == null) {
        return auth_ == null ? com.lightstep.tracer.grpc.Auth.getDefaultInstance() : auth_;
      } else {
        return authBuilder_.getMessage();
      }
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public Builder setAuth(com.lightstep.tracer.grpc.Auth value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        auth_ = value;
        onChanged();
      } else {
        authBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public Builder setAuth(
        com.lightstep.tracer.grpc.Auth.Builder builderForValue) {
      if (authBuilder_ == null) {
        auth_ = builderForValue.build();
        onChanged();
      } else {
        authBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public Builder mergeAuth(com.lightstep.tracer.grpc.Auth value) {
      if (authBuilder_ == null) {
        if (auth_ != null) {
          auth_ =
            com.lightstep.tracer.grpc.Auth.newBuilder(auth_).mergeFrom(value).buildPartial();
        } else {
          auth_ = value;
        }
        onChanged();
      } else {
        authBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public Builder clearAuth() {
      if (authBuilder_ == null) {
        auth_ = null;
        onChanged();
      } else {
        auth_ = null;
        authBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public com.lightstep.tracer.grpc.Auth.Builder getAuthBuilder() {
      
      onChanged();
      return getAuthFieldBuilder().getBuilder();
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    public com.lightstep.tracer.grpc.AuthOrBuilder getAuthOrBuilder() {
      if (authBuilder_ != null) {
        return authBuilder_.getMessageOrBuilder();
      } else {
        return auth_ == null ?
            com.lightstep.tracer.grpc.Auth.getDefaultInstance() : auth_;
      }
    }
    /**
     * <code>.lightstep.collector.Auth auth = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.Auth, com.lightstep.tracer.grpc.Auth.Builder, com.lightstep.tracer.grpc.AuthOrBuilder> 
        getAuthFieldBuilder() {
      if (authBuilder_ == null) {
        authBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lightstep.tracer.grpc.Auth, com.lightstep.tracer.grpc.Auth.Builder, com.lightstep.tracer.grpc.AuthOrBuilder>(
                getAuth(),
                getParentForChildren(),
                isClean());
        auth_ = null;
      }
      return authBuilder_;
    }

    private java.util.List<com.lightstep.tracer.grpc.Span> spans_ =
      java.util.Collections.emptyList();
    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        spans_ = new java.util.ArrayList<com.lightstep.tracer.grpc.Span>(spans_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.lightstep.tracer.grpc.Span, com.lightstep.tracer.grpc.Span.Builder, com.lightstep.tracer.grpc.SpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public java.util.List<com.lightstep.tracer.grpc.Span> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public com.lightstep.tracer.grpc.Span getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder setSpans(
        int index, com.lightstep.tracer.grpc.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder setSpans(
        int index, com.lightstep.tracer.grpc.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder addSpans(com.lightstep.tracer.grpc.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder addSpans(
        int index, com.lightstep.tracer.grpc.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder addSpans(
        com.lightstep.tracer.grpc.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder addSpans(
        int index, com.lightstep.tracer.grpc.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder addAllSpans(
        java.lang.Iterable<? extends com.lightstep.tracer.grpc.Span> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public com.lightstep.tracer.grpc.Span.Builder getSpansBuilder(
        int index) {
      return getSpansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public com.lightstep.tracer.grpc.SpanOrBuilder getSpansOrBuilder(
        int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);  } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public java.util.List<? extends com.lightstep.tracer.grpc.SpanOrBuilder> 
         getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public com.lightstep.tracer.grpc.Span.Builder addSpansBuilder() {
      return getSpansFieldBuilder().addBuilder(
          com.lightstep.tracer.grpc.Span.getDefaultInstance());
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public com.lightstep.tracer.grpc.Span.Builder addSpansBuilder(
        int index) {
      return getSpansFieldBuilder().addBuilder(
          index, com.lightstep.tracer.grpc.Span.getDefaultInstance());
    }
    /**
     * <code>repeated .lightstep.collector.Span spans = 3;</code>
     */
    public java.util.List<com.lightstep.tracer.grpc.Span.Builder> 
         getSpansBuilderList() {
      return getSpansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.lightstep.tracer.grpc.Span, com.lightstep.tracer.grpc.Span.Builder, com.lightstep.tracer.grpc.SpanOrBuilder> 
        getSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.lightstep.tracer.grpc.Span, com.lightstep.tracer.grpc.Span.Builder, com.lightstep.tracer.grpc.SpanOrBuilder>(
                spans_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }

    private long timestampOffsetMicros_ ;
    /**
     * <code>int64 timestamp_offset_micros = 5;</code>
     */
    public long getTimestampOffsetMicros() {
      return timestampOffsetMicros_;
    }
    /**
     * <code>int64 timestamp_offset_micros = 5;</code>
     */
    public Builder setTimestampOffsetMicros(long value) {
      
      timestampOffsetMicros_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_offset_micros = 5;</code>
     */
    public Builder clearTimestampOffsetMicros() {
      
      timestampOffsetMicros_ = 0L;
      onChanged();
      return this;
    }

    private com.lightstep.tracer.grpc.InternalMetrics internalMetrics_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.InternalMetrics, com.lightstep.tracer.grpc.InternalMetrics.Builder, com.lightstep.tracer.grpc.InternalMetricsOrBuilder> internalMetricsBuilder_;
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public boolean hasInternalMetrics() {
      return internalMetricsBuilder_ != null || internalMetrics_ != null;
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public com.lightstep.tracer.grpc.InternalMetrics getInternalMetrics() {
      if (internalMetricsBuilder_ == null) {
        return internalMetrics_ == null ? com.lightstep.tracer.grpc.InternalMetrics.getDefaultInstance() : internalMetrics_;
      } else {
        return internalMetricsBuilder_.getMessage();
      }
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public Builder setInternalMetrics(com.lightstep.tracer.grpc.InternalMetrics value) {
      if (internalMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        internalMetrics_ = value;
        onChanged();
      } else {
        internalMetricsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public Builder setInternalMetrics(
        com.lightstep.tracer.grpc.InternalMetrics.Builder builderForValue) {
      if (internalMetricsBuilder_ == null) {
        internalMetrics_ = builderForValue.build();
        onChanged();
      } else {
        internalMetricsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public Builder mergeInternalMetrics(com.lightstep.tracer.grpc.InternalMetrics value) {
      if (internalMetricsBuilder_ == null) {
        if (internalMetrics_ != null) {
          internalMetrics_ =
            com.lightstep.tracer.grpc.InternalMetrics.newBuilder(internalMetrics_).mergeFrom(value).buildPartial();
        } else {
          internalMetrics_ = value;
        }
        onChanged();
      } else {
        internalMetricsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public Builder clearInternalMetrics() {
      if (internalMetricsBuilder_ == null) {
        internalMetrics_ = null;
        onChanged();
      } else {
        internalMetrics_ = null;
        internalMetricsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public com.lightstep.tracer.grpc.InternalMetrics.Builder getInternalMetricsBuilder() {
      
      onChanged();
      return getInternalMetricsFieldBuilder().getBuilder();
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    public com.lightstep.tracer.grpc.InternalMetricsOrBuilder getInternalMetricsOrBuilder() {
      if (internalMetricsBuilder_ != null) {
        return internalMetricsBuilder_.getMessageOrBuilder();
      } else {
        return internalMetrics_ == null ?
            com.lightstep.tracer.grpc.InternalMetrics.getDefaultInstance() : internalMetrics_;
      }
    }
    /**
     * <code>.lightstep.collector.InternalMetrics internal_metrics = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lightstep.tracer.grpc.InternalMetrics, com.lightstep.tracer.grpc.InternalMetrics.Builder, com.lightstep.tracer.grpc.InternalMetricsOrBuilder> 
        getInternalMetricsFieldBuilder() {
      if (internalMetricsBuilder_ == null) {
        internalMetricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lightstep.tracer.grpc.InternalMetrics, com.lightstep.tracer.grpc.InternalMetrics.Builder, com.lightstep.tracer.grpc.InternalMetricsOrBuilder>(
                getInternalMetrics(),
                getParentForChildren(),
                isClean());
        internalMetrics_ = null;
      }
      return internalMetricsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lightstep.collector.ReportRequest)
  }

  // @@protoc_insertion_point(class_scope:lightstep.collector.ReportRequest)
  private static final com.lightstep.tracer.grpc.ReportRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lightstep.tracer.grpc.ReportRequest();
  }

  public static com.lightstep.tracer.grpc.ReportRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReportRequest>() {
    @java.lang.Override
    public ReportRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lightstep.tracer.grpc.ReportRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

